services:
  db:
    image: postgres:15
    container_name: pixelartavenue_db_container_prod
    restart: always
    env_file:
      - .env
    volumes:
      - pixelartavenue_db_data_prod:/var/lib/postgresql/data

  api:
    image: lstz/api.pixelartavenue:latest
    container_name: pixelartavenue_api_container_prod
    restart: always
    env_file:
      - .env
    ports:
      - '3101:3101'
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pixelartavenue_pgadmin_container_prod
    restart: always
    env_file:
      - .env.pgadmin
    ports:
      - '3102:80'
    depends_on:
      - db
    volumes:
      - pixelartavenue_pgadmin_data_prod:/var/lib/pgadmin

volumes:
  pixelartavenue_db_data_prod:
    driver: local
    name: pixelartavenue_db_data_prod
  pixelartavenue_pgadmin_data_prod:
    driver: local
    name: pixelartavenue_pgadmin_data_prod

networks:
  default:
    name: pixelart-network
    external: true
