services:
  db:
    image: postgres:15
    container_name: pixelartavenue_db_container_dev
    restart: always
    env_file:
      - .env
    volumes:
      - pixelartavenue_db_data_dev:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: pixelartavenue_api_container_dev
    restart: always
    env_file:
      - .env
    ports:
      - '3111:3101'
    depends_on:
      - db
    volumes:
      - .:/app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pixelartavenue_pgadmin_container_dev
    restart: always
    env_file:
      - .env.pgadmin
    ports:
      - '3112:80'
    depends_on:
      - db
    volumes:
      - pixelartavenue_pgadmin_data_dev:/var/lib/pgadmin

volumes:
  pixelartavenue_db_data_dev:
    driver: local
    name: pixelartavenue_db_data_dev
  pixelartavenue_pgadmin_data_dev:
    driver: local
    name: pixelartavenue_pgadmin_data_dev

networks:
  default:
    name: pixelart-network
    external: true
