name : CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
    
          - name: Login to DockerHub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v6
            with:
                context: .
                push: true
                file: ./Dockerfile
                target: prod
                tags: ${{ secrets.DOCKER_USERNAME }}/api.pixelartavenue:latest

    deploy:
        needs: build
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
    
          - name: Configure SSH
            uses: webfactory/ssh-agent@v0.9.0
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
          - name: Copy docker-compose file
            uses: appleboy/scp-action@v0.1.7
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              source: './docker-compose.prod.yml'
              target: '/home/${{ secrets.SSH_USER }}/pixelartproject/api.pixelartavenue'

          - name: Create .env file
            run: |
              echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
              echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
              echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
              echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
              echo PORT=${{ secrets.PORT }} >> .env          
    
          - name: Copy .env file
            uses: appleboy/scp-action@v0.1.7
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              source: './.env'
              target: '/home/${{ secrets.SSH_USER }}/pixelartproject/api.pixelartavenue'

          - name: Deploy to VPS
            run: |
              ssh -o "StrictHostKeyChecking=no" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
              cd /home/${{ secrets.SSH_USER }}/pixelartproject/api.pixelartavenue
              docker-compose -f docker-compose.prod.yml down
              docker-compose -f docker-compose.prod.yml pull
              docker-compose -f docker-compose.prod.yml up -d
              EOF

# Penser que le fichier .env est saisi manuellement dans le serveur distant.